#ifndef ENGINETEST_GLOBAL_H
#define ENGINETEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENGINETEST_LIBRARY)
#  define ENGINETESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ENGINETESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ENGINETEST_GLOBAL_H
